apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    k8s-app: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      k8s-app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        k8s-app: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}
{{- if .Values.deploy.affinity }}
      affinity:
{{ toYaml .Values.deploy.affinity | indent 8 }}
{{- end }}
{{- if .Values.deploy.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.deploy.nodeSelector | indent 8 }}
{{- end }}
      hostNetwork: {{ .Values.deploy.hostNetwork }}
      containers:
      - name: "kubemutator"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: {{ .Values.image.name }}
        args: ["--listen", ":{{ .Values.deploy.listenPort }}"]
        ports:
        - name: https
          containerPort: {{ .Values.deploy.listenPort }}
        volumeMounts:
        - name: config
          mountPath: /etc/kubemutator
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }}
