apiVersion:  admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "kubemutator"
  labels:
    app: kubemutator
webhooks:
  - name: kubemutator.example.com
    failurePolicy: "Ignore" # we fail "open" if the webhook is down hard
    namespaceSelector:
      matchLabels:
        name: default
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    clientConfig:
      service:
        name: "kubemutator"
        namespace: "kube-system"
        path: "/mutate"
      caBundle: "!!! your base64 encoded cabundle here !!!"
    sideEffects: None
    admissionReviewVersions: ["v1"]
